"""Hyprland backend protocol. All version-specific dispatch strings live here."""

from typing import Protocol


class Backend(Protocol):
    name: str

    async def query(self, command: str): ...
    async def focus_window(self, target: str) -> str: ...
    async def close_window(self, target: str | None) -> str: ...
    async def move_window(self, x: int | None, y: int | None,
                          workspace: str | None, target: str | None) -> str: ...
    async def resize_window(self, width: int, height: int, target: str | None) -> str: ...
    async def toggle_fullscreen(self, mode: str) -> str: ...
    async def toggle_floating(self, target: str | None) -> str: ...
    async def switch_workspace(self, workspace: str) -> str: ...
    async def move_cursor(self, x: int, y: int) -> None: ...
    async def send_shortcut(self, mods: str, key: str, target: str | None) -> str: ...
    async def launch(self, command: str) -> str: ...
